# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: "Makers Vs CoViD-19 and SARS-CoV-2 - StartPoint"
email: 
description: "Ponto de entrada para os Makers que desejam desenvolver projetos contra a CoViD-19"
baseurl: "/StartPoint"
url: ""
twitter_username: ""
github_username:  "makers-vs-covid-19/startpoint"
color_theme:  "#0081ff"
color_text:  "#fff"
language:  "en"

excerpt_separator: "<!--more-->"

# Build settings
markdown: kramdown
permalink: /:title/
plugins: [jekyll-paginate]
paginate: 5

# Plugins
plugins_dir:
  - jekyll-admin
